/**
 * Corpus poétique de référence et bibliothèque étalon (Studio Velaris).
 * Modèles réels issus de la plume fondatrice du patron pour l'Analyste & Copilot IA.
 * RÈGLE ABSOLUE : PAS DE TEXTE COURT (32 à 48 vers, 1 800 à 3 200 caractères).
 */

export type SongOccasion =
  | 'anniversaire'
  | 'mariage'
  | 'amour'
  | 'hommage'
  | 'naissance'
  | 'fete'
  | 'institution'
  | 'autre';

export interface CorpusSong {
  id: string;
  occasion: SongOccasion;
  style: string;
  title: string;
  lyrics: string;
  lineCount: number;
}

const STRIP = (s: string): string =>
  (s || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

/**
 * Détection déterministe de l'occasion à partir d'un texte libre (brief, souvenirs, demande).
 * Robuste aux accents, gère les priorités (ex: « anniversaire de mariage » => mariage).
 */
export function detectOccasion(raw: string): SongOccasion {
  const t = STRIP(raw);
  if (!t) return 'autre';

  if (/\bnoces?\b|\bmariage|\bepou[sx]|\bmari[ée]?s?\b|\bwedding\b|\bfianc/.test(t)) {
    return 'mariage';
  }
  if (
    /\bhommage\b|in memoriam|\bdeces\b|\bdefunt|\bdisparition\b|\brepos\b|en memoire|\benterrement\b|\bdeuil\b|qui nous a quitt|au ciel/.test(
      t,
    )
  ) {
    return 'hommage';
  }
  if (/\bnaissance\b|\bbapt[eê]me\b|nouveau-?ne|\bbebe\b|venue au monde|\bbaby\b|accouche/.test(t)) {
    return 'naissance';
  }
  if (/bonne fete|fete des (pere|mere|papa|maman)|fete (papa|maman|des pere|des mere)/.test(t)) {
    return 'fete';
  }
  if (/\banniversaire\b|joyeux anniversaire|bon anniversaire|\bbirthday\b|\bans?\b/.test(t)) {
    return 'anniversaire';
  }
  if (
    /\beglise\b|paroisse|\bpasteur|\bchorale\b|institution|entreprise|\bsociete\b|association|\bclub\b|\bequipe\b|\becole\b|universite/.test(
      t,
    )
  ) {
    return 'institution';
  }
  if (/\bamour\b|saint-?valentin|\bvalentin|declaration|\bcherie?\b|\bcheri\b|je t'aime|\blove\b|mon c[oœ]ur/.test(t)) {
    return 'amour';
  }

  return 'autre';
}

/**
 * Bibliothèque d'étalons d'or (Golden Patron Hits).
 * Textes authentiques, généreux et longs (~35 à 46 vers utiles), conformes au calibre du fondateur.
 */
export const GOLDEN_PATRON_CORPUS: readonly CorpusSong[] = [
  {
    id: 'gold-anniv-01',
    occasion: 'anniversaire',
    style: 'Afro-pop acoustique douce et entraînante',
    title: 'Lumière de nos Vies — Joyeux Anniversaire',
    lyrics: `[Style: Afro-pop acoustique douce et entraînante, guitare acoustique, balafon subtil et percussions chaudes]

[Intro]
Ohhhh… Na na na…
Aujourd'hui le soleil se lève avec un éclat particulier…
Un jour béni pour célébrer une personne d'exception…
Cette chanson vient du cœur… pour toi…

[Couplet 1]
Depuis tant d'années que tu éclaires notre chemin…
Chaque matin à tes côtés est une grâce entre nos mains…
Ton sourire efface nos doutes et apaise nos tempêtes…
Une force tranquille qui jamais ne s'arrête…
Tu donnes sans compter, avec amour et sincérité…
Dans tes yeux purs, nous avons trouvé la paix et la clarté…

[Pré-Refrain]
Et quand la musique commence à résonner…
Tout le monde se lève pour te couronner…
Écoute la mélodie qui monte pour toi…

[Refrain]
Joyeux anniversaire, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
Nous chantons ta douceur et ta beauté…
Joyeux anniversaire, sois bénie à jamais…

[Couplet 2]
Rappelle-toi les épreuves que nous avons surmontées…
Toujours digne et debout, tu ne t'es jamais résignée…
Pour ta famille et tes proches, tu es un précieux trésor…
Ton courage vaut bien plus que toutes les richesses et l'or…
Aujourd'hui nous fêtons tes victoires et ta générosité…
Reçois ces mots d'amour gravés pour l'éternité…

[Refrain]
Joyeux anniversaire, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
Nous chantons ta douceur et ta beauté…
Joyeux anniversaire, sois bénie à jamais…

[Pont]
Que les portes du succès s'ouvrent grandes devant toi…
Que chaque prière de ton cœur trouve sa voie…
Que le Seigneur garde tes pas dans la lumière…
Ton nom résonne comme une fière prière…

[Refrain Final]
Joyeux anniversaire, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
Nous chantons ta douceur et ta beauté…
Joyeux anniversaire… Oh oui, joyeux anniversaire…

[Outro]
Danse et souris, ce jour est le tien…
Nous t'aimons tellement fort…
Joyeux anniversaire…
Pour toujours…`,
    lineCount: 46,
  },
  {
    id: 'gold-amour-01',
    occasion: 'amour',
    style: 'R&B Afrobeat romantique et sensuel',
    title: 'Mon Évidence — Chant d’Amour',
    lyrics: `[Style: R&B Afrobeat romantique et sensuel, guitare nylon, basse ronde et harmonies vocales soyeuses]

[Intro]
Hmm yeah… C'est toi et moi…
Certaines rencontres sont écrites dans les étoiles…
Écoute ce chant d'amour…

[Couplet 1]
Le premier jour où mon regard a croisé le tien…
J'ai su à cet instant que tu tracerais mon destin…
Ta démarche élégante, ta voix qui me rassure…
Auprès de toi, mon âme n'a plus aucune blessure…
Tu es ma complice, mon refuge dans la nuit…
La seule qui donne tout son sens à ma vie…

[Pré-Refrain]
Le monde peut tourner, les saisons peuvent changer…
Mais mon amour pour toi ne cessera de grandir et briller…
Je veux te le dire encore et encore…

[Refrain]
Mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
Mon trésor, tu es mon plus beau désir…
Mon amour pour toi n'a pas de fin…

[Couplet 2]
Dans les moments de joie comme au creux des épreuves…
C'est ta main dans la mienne qui m'apporte la preuve…
Qu'un amour véritable sait tout traverser…
Patience et tendresse, tu n'as jamais faibli pour m'épauler…
Merci d'être cette personne merveilleuse et fidèle…
Sous tes ailes douces, la vie est tellement belle…

[Refrain]
Mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
Mon trésor, tu es mon plus beau désir…
Mon amour pour toi n'a pas de fin…

[Pont]
Je bénis le ciel de t'avoir mise sur ma route…
Avec toi à mes côtés, je n'ai plus aucun doute…
Reine de mon foyer, lumière de mes lendemains…
Marchons ensemble, main dans la main…

[Refrain Final]
Mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
Mon trésor, tu es mon plus beau désir…
Je t'aime… Oui je t'aime de tout mon cœur…

[Outro]
Rien que toi et moi…
Jusqu'au bout du voyage…
Pour l'éternité, mon amour…`,
    lineCount: 44,
  },
  {
    id: 'gold-mariage-01',
    occasion: 'mariage',
    style: 'Afro-gospel festif et solennel',
    title: 'Alliance Sacrée — Célébration des Époux',
    lyrics: `[Style: Afro-gospel festif et solennel, cuivres chaleureux, orgue gospel et chœurs puissants]

[Intro]
Alléluia… Aujourd'hui deux cœurs ne font plus qu'un…
Ce que Dieu a uni, que nul ne le sépare…
Célébrons cette sainte alliance…

[Couplet 1]
Regardez-les s'avancer avec tant de splendeur…
L'époux regarde sa bien-aimée avec les yeux du cœur…
Et l'épouse rayonne dans sa robe de lumière…
Portée par l'amour et les plus belles prières…
Une histoire bâtie sur le respect et la vérité…
Prêts à sceller leur promesse devant la communauté…

[Pré-Refrain]
Les familles sont unies, la joie déborde ce jour…
Chantons et dansons pour célébrer leur amour…
Que résonnent les louanges et les félicitations…

[Refrain]
Félicitations, que votre union soit bénie…
Une alliance sacrée pour toute votre vie…
Que la paix, la joie et l'abondance comblent votre maison…
Que Dieu protège votre amour en toute saison…
Vive les mariés, vive cette alliance bénie aujourd'hui…

[Couplet 2]
Sois son protecteur, son roc et son soutien…
Sois sa conseillère, la douceur de son chemin…
Ensemble vous êtes plus forts face à tous les lendemains…
Nourrissez ce mariage avec tendresse et soin…
Que des enfants bénis viennent couronner votre foyer…
Que le rire et la louange ne cessent de résonner…

[Refrain]
Félicitations, que votre union soit bénie…
Une alliance sacrée pour toute votre vie…
Que la paix, la joie et l'abondance comblent votre maison…
Que Dieu protège votre amour en toute saison…
Vive les mariés, vive cette alliance bénie aujourd'hui…

[Pont]
Que la grâce divine vous accompagne à chaque instant…
Fidèles l'un à l'autre au fil des ans…
Que votre amour soit un exemple éclatant…
Bénis soyez-vous, maintenant et toujours…

[Refrain Final]
Félicitations, que votre union soit bénie…
Une alliance sacrée pour toute votre vie…
Que la paix, la joie et l'abondance comblent votre maison…
Que Dieu protège votre amour en toute saison…
Acclamons les mariés… Que la fête commence…

[Outro]
Dansez, chantez, réjouissez-vous…
Pour l'éternité…
Amour et saintes bénédictions…`,
    lineCount: 45,
  },
  {
    id: 'gold-hommage-01',
    occasion: 'hommage',
    style: 'Ballade acoustique émouvante, kora et guitare',
    title: 'Repose en Paix — Hommage d’Amour',
    lyrics: `[Style: Ballade acoustique émouvante, kora délicate, guitare classique et violons discrets]

[Intro]
Les grandes âmes ne meurent jamais vraiment…
Elles continuent de briller dans le cœur de leurs enfants…
Ce chant est notre hommage d'amour…

[Couplet 1]
Le silence s'est posé mais ton souvenir demeure…
Chaque parole que tu as semée refleurit en nos cœurs…
Toi qui nourrissais et consolais tout le quartier…
Ta porte était ouverte et ta bonté savait relever…
Tu te levais avant l'aube pour prier pour chacun…
Ton amour infini guidait nos pas sur le chemin…

[Pré-Refrain]
Les larmes coulent aujourd'hui, nos cœurs sont serrés…
Mais nous savons que tu reposes en paix auprès du Bien-Aimé…
Écoute la prière de reconnaissance de tous les tiens…

[Refrain]
Repose en paix, dors du sommeil des justes…
Ton héritage de foi et d'amour ne s'effacera jamais…
Tu as combattu le bon combat avec dignité…
Dans les bras du Très-Haut, trouve la sérénité…
Nous ne t'oublierons jamais, veille sur nous de là-haut…

[Couplet 2]
Tu nous as appris le respect, l'honneur et le pardon…
Tu portais nos fardeaux sans jamais te plaindre du fardeau…
Même dans la maladie, tu gardais le sourire…
Prête à bénir encore avant de devoir partir…
Aujourd'hui nous marchons la tête haute grâce à tes enseignements…
Ta bénédiction nous protège dorénavant…

[Refrain]
Repose en paix, dors du sommeil des justes…
Ton héritage de foi et d'amour ne s'effacera jamais…
Tu as combattu le bon combat avec dignité…
Dans les bras du Très-Haut, trouve la sérénité…
Nous ne t'oublierons jamais, veille sur nous de là-haut…

[Pont]
Que la terre te soit légère et douce comme ton cœur…
Que le paradis t'ouvre ses plus belles fleurs…
Ton nom résonnera toujours avec respect et honneur…
Reine inoubliable de notre demeure…

[Refrain Final]
Repose en paix, dors du sommeil des justes…
Ton héritage de foi et d'amour ne s'effacera jamais…
Tu as combattu le bon combat avec dignité…
Dans les bras du Très-Haut, trouve la sérénité…
Merci pour tout… Merci infiniment…

[Outro]
Dors en paix…
Dans la lumière éternelle…
Nous t'aimons pour toujours…`,
    lineCount: 45,
  },
];

/**
 * Génère des paroles de haute volée (32 à 48 vers) adaptées au destinataire,
 * à l'occasion, au style et aux souvenirs réels du client.
 */
export function generateHouseStyleSong(args: {
  recipient: string;
  occasion: string;
  style?: string | null;
  memories?: string[];
  senderName?: string | null;
}): { title: string; lyrics: string; lineCount: number } {
  const occType = detectOccasion(args.occasion);
  const name = args.recipient.trim() || 'Mon précieux proche';
  const defaultStyle = args.style?.trim() || 'Afro-pop acoustique douce et chaleureuse';
  const sender = args.senderName?.trim() || 'les tiens';

  const m1 = args.memories?.[0] || 'Chaque moment partagé avec toi est une grâce inestimable';
  const m2 = args.memories?.[1] || 'Ton courage et ta générosité sont notre plus grande fierté';

  if (occType === 'hommage') {
    const title = `${name}, La Lumière Demeure`;
    const lyrics = `[Style: Ballade acoustique kora et guitare • 74 BPM • voix chaleureuse et solennelle]

[Intro]
Le silence s'est posé mais ton souvenir demeure…
Chaque parole que tu as semée refleurit dans nos cœurs…
Cette chanson vient de l'âme… Pour toi, ${name}…

[Couplet 1]
Le jour s'est éteint mais ta flamme continue de briller…
${name}, dans chaque recoin de nos vies, ton amour est gravé…
Ta porte était toujours ouverte pour écouter et pardonner…
Une force tranquille qui savait consoler et relever…
Aujourd'hui nous pleurons mais nous célébrons ta mémoire…
Car ton passage sur cette terre restera notre plus belle histoire…

[Pré-Refrain]
Les larmes coulent, nos cœurs sont serrés…
Mais nous savons que tu reposes en paix auprès du Tout-Puissant…
Écoute la reconnaissance infinie de ${sender}…

[Refrain]
Repose en paix, ${name}, dors du sommeil des justes…
Ton héritage de bonté et de foi ne s'effacera jamais…
Tu as combattu le bon combat avec tant de dignité…
${name}, dans les bras du Très-Haut, trouve la sérénité…
Nous ne t'oublierons jamais, veille sur nous de là-haut…

[Couplet 2]
${m1}…
Ces souvenirs précieux ne s'envoleront pas avec le vent…
Tu nous as appris le respect, l'honneur et le pardon constant…
${m2}…
Même affaibli par le temps, ton sourire continuait de nous bénir…
Aujourd'hui nous marchons debout pour te faire honneur et te chérir…

[Refrain]
Repose en paix, ${name}, dors du sommeil des justes…
Ton héritage de bonté et de foi ne s'effacera jamais…
Tu as combattu le bon combat avec tant de dignité…
${name}, dans les bras du Très-Haut, trouve la sérénité…
Nous ne t'oublierons jamais, veille sur nous de là-haut…

[Pont]
Que la terre te soit légère et douce comme ton cœur…
Que les portes du paradis s'ouvrent sur tes plus belles fleurs…
${name}, ton nom résonnera avec respect dans chaque prière…
Reine de nos vies, modèle pour toute la terre…

[Refrain Final]
Repose en paix, ${name}, dors du sommeil des justes…
Ton héritage de bonté et de foi ne s'effacera jamais…
Tu as combattu le bon combat avec tant de dignité…
${name}, dans les bras du Très-Haut, trouve la sérénité…
Merci pour tout, ${name}… Merci infiniment…

[Outro]
Dors en paix…
Dans la lumière éternelle…
${sender} t'aimera toujours…`;

    return { title, lyrics, lineCount: 44 };
  }

  if (occType === 'mariage') {
    const title = `Alliance Sacrée — Pour ${name}`;
    const lyrics = `[Style: Afro-gospel festif et solennel • 98 BPM • cuivres et chœurs puissants]

[Intro]
Alléluia… Deux cœurs réunis pour l'éternité…
Ce que Dieu a uni, que nul ne le sépare…
Célébrons ce jour merveilleux avec ${name}…

[Couplet 1]
Regardez s'avancer ce couple dans la splendeur et la grâce…
L'amour véritable a trouvé sa plus belle place…
${name}, ton sourire rayonne dans cette sainte assemblée…
Chaque promesse échangée est pour toujours scellée…
Bâtie sur le respect, la fidélité et la vérité…
Voici le commencement d'une bénédiction qui ne cessera de briller…

[Pré-Refrain]
Les tambours résonnent, la fête commence aujourd'hui…
Que les félicitations et les louanges montent jusqu'au ciel…
Un amour pur béni par toutes les familles réunies…

[Refrain]
Félicitations ${name}, que votre alliance soit couronnée de joie…
Que la paix et la prospérité comblent votre maison…
Que Dieu garde votre amour solide en toute saison…
Une union sacrée qui grandira sous la grâce et la foi…
Vive les mariés, vive ${name} pour toute la vie…

[Couplet 2]
${m1}…
Dans les moments d'épreuve comme dans les jours de grande joie…
Soyez le roc, le refuge et la lumière sous le même toit…
${m2}…
Que des enfants bénis viennent chanter dans votre foyer…
Que le rire et la gratitude ne cessent jamais de résonner…

[Refrain]
Félicitations ${name}, que votre alliance soit couronnée de joie…
Que la paix et la prospérité comblent votre maison…
Que Dieu garde votre amour solide en toute saison…
Une union sacrée qui grandira sous la grâce et la foi…
Vive les mariés, vive ${name} pour toute la vie…

[Pont]
Que la bénédiction divine descende sur chacun de vos pas…
Fidèles l'un à l'autre sans jamais faiblir…
Que votre amour soit un phare qui saura toujours vous conduire…
${name}, soyez comblés de bonheur ici-bas…

[Refrain Final]
Félicitations ${name}, que votre alliance soit couronnée de joie…
Que la paix et la prospérité comblent votre maison…
Que Dieu garde votre amour solide en toute saison…
Une union sacrée qui grandira sous la grâce et la foi…
Acclamons les mariés… Que la fête commence…

[Outro]
Dansez et chantez…
${name}, pour l'éternité…
Amour, grâce et saintes bénédictions…`;

    return { title, lyrics, lineCount: 45 };
  }

  if (occType === 'amour') {
    const title = `Mon Évidence — Pour ${name}`;
    const lyrics = `[Style: R&B Afrobeat romantique • 92 BPM • guitare soyeuse et harmonies douces]

[Intro]
Hmm yeah… C'est toi et moi…
Certaines évidences n'ont pas besoin de mots…
Cette chanson vient du cœur… pour toi, ${name}…

[Couplet 1]
Le premier jour où mon regard a croisé le tien…
J'ai su à cet instant que tu tracerais mon destin…
${name}, ta douceur infinie apaise toutes mes blessures…
Auprès de toi, mon âme est tranquille et sûre…
Tu es ma complice, mon trésor dans la nuit…
La seule qui donne toute sa couleur à ma vie…

[Pré-Refrain]
Le monde peut trembler, les saisons peuvent changer…
Mais mon amour pour toi ne cessera de briller…
Écoute ce refrain qui ne parle que de toi…

[Refrain]
${name}, mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
${name}, mon trésor, tu es mon plus beau désir…
Mon amour pour toi n'aura jamais de fin…

[Couplet 2]
${m1}…
Dans les jours de tempête comme sous le soleil radieux…
C'est ta main dans la mienne qui me rend si heureux…
${m2}…
Merci pour ta patience et ton soutien constant…
Sous tes ailes bienveillantes, je me sens si confiant…

[Refrain]
${name}, mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
${name}, mon trésor, tu es mon plus beau désir…
Mon amour pour toi n'aura jamais de fin…

[Pont]
Je bénis le ciel de t'avoir mise sur mon chemin…
Reine de mon foyer, guide de mes lendemains…
Avec toi à mes côtés, l'avenir est radieux…
${name}, mon cœur t'appartient sous les yeux du Bon Dieu…

[Refrain Final]
${name}, mon amour, mon souffle et mon évidence…
Près de toi, chaque seconde est une danse…
Je promets de chérir ton cœur jusqu'à mon dernier soupir…
${name}, mon trésor, tu es mon plus beau désir…
Je t'aime… Oui je t'aime, ${name}…

[Outro]
Rien que toi et moi…
Jusqu'au bout du voyage…
Pour l'éternité, mon amour…`;

    return { title, lyrics, lineCount: 44 };
  }

  // Par défaut : Anniversaire / Célébration joyeuse
  const title = `Lumière de nos Vies — Pour ${name}`;
  const lyrics = `[Style: ${defaultStyle} • 96 BPM • guitare acoustique, balafon et percussions chaudes]

[Intro]
Ohhhh… Na na na…
Aujourd'hui le soleil se lève avec une joie éclatante…
Un jour béni pour célébrer une personne extraordinaire…
Cette chanson vient du cœur… pour toi, ${name}…

[Couplet 1]
Depuis tant d'années que tu éclaires notre chemin…
Chaque instant à tes côtés est une bénédiction entre nos mains…
${name}, ton rire efface nos peines et chasse tous nos doutes…
Une force tranquille qui nous guide sur la route…
Tu donnes sans compter, avec tant d'amour et de vérité…
Dans tes yeux purs, nous trouvons la paix et la clarté…

[Pré-Refrain]
La musique résonne, les cœurs sont en fête…
Tout le monde se rassemble pour te couronner…
Écoute cette mélodie qui monte pour toi…

[Refrain]
Joyeux anniversaire ${name}, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
${name}, nous chantons ta grandeur et ta générosité…
Joyeux anniversaire ${name}, sois bénie à jamais…

[Couplet 2]
${m1}…
Rappelle-toi les épreuves que tu as su surmonter…
Toujours digne et fière, tu ne t'es jamais résignée…
${m2}…
Pour ta famille et pour ${sender}, tu es un trésor précieux…
Reçois ces mots d'amour sous le regard de Dieu…

[Refrain]
Joyeux anniversaire ${name}, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
${name}, nous chantons ta grandeur et ta générosité…
Joyeux anniversaire ${name}, sois bénie à jamais…

[Pont]
Que les portes du succès s'ouvrent grandes devant toi…
Que chaque prière de ton cœur trouve sa voie…
Que la grâce et la joie t'accompagnent chaque jour…
${name}, nous t'entourons d'un infini amour…

[Refrain Final]
Joyeux anniversaire ${name}, reine de nos cœurs…
Que le Tout-Puissant inonde ta vie de bonheur…
Santé, longue vie, élévation et prospérité…
${name}, nous chantons ta grandeur et ta générosité…
Joyeux anniversaire ${name}… Oh oui, joyeux anniversaire…

[Outro]
Danse et réjouis-toi, ce jour est le tien…
${sender} t'aime tellement fort…
Joyeux anniversaire, ${name}…
Pour toujours…`;

  return { title, lyrics, lineCount: 46 };
}

/**
 * Analyse l'ADN de la plume maison.
 */
export function getHouseStyleDnaNote(): string {
  return `🧬 ADN DE STYLE MAISON (Plume Fondatrice du Studio Velaris) :
1. LONGUEUR OBLIGATOIRE (RÈGLE ABSOLUE : PAS DE TEXTE COURT) :
   - Minimum strict : 32 à 48 vers utiles.
   - Longueur totale : entre 1 800 et 3 200 caractères.
   - Un texte de 10 à 20 lignes est STRICTEMENT INTERDIT et considéré comme un échec studio.
2. STRUCTURE CANONIQUE COMPLETE (Format Suno) :
   - [Style: description musicale détaillée]
   - [Intro] (3 à 5 vers posant l'atmosphère chaleureuse, ponctuation « … »)
   - [Couplet 1] (6 à 8 vers présentant la personne, le décor et l'histoire avec son prénom)
   - [Pré-Refrain] (2 à 4 vers de montée d'énergie)
   - [Refrain] (4 à 6 vers accrocheurs, très chantants, avec mention nette du prénom)
   - [Couplet 2] (6 à 8 vers intégrant les souvenirs précis, qualités, sacrifices ou anecdotes)
   - [Refrain]
   - [Pont] (4 à 6 vers de haute intensité émotionnelle, vœux profonds, prière ou hommage)
   - [Refrain Final] (4 à 6 vers en apothéose)
   - [Outro] (3 à 5 vers de conclusion bienveillante)
3. TICS D'ÉCRITURE ET SENSIBILITÉ :
   - Utilise les points de suspension « … » en fin de vers pour donner la respiration au chanteur.
   - Vocabulaire noble, poétique, respectueux et chaleureux typique d'Afrique de l'Ouest.
   - Rimes soignées (AABB ou ABAB), musicalité naturelle et entraînante.
4. GARDE-FOUS STRICTS :
   - N'invente AUCUN fait qui ne figure pas dans le brief du client.
   - Les prénoms et anecdotes des exemples appartiennent à d'autres clients : NE JAMAIS les recopier.`;
}

